[package]
name = "macro_function_test_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macro_function = {path = "macro_function"}

[lib]
proc-macro = true
